import {useState} from 'react';
import {NavLink, Outlet, useLocation} from 'react-router-dom';
import {LayoutDashboard, GitBranch, PlugZap, Braces, ShieldCheck, ScrollText, HeartPulse, CircleAlert, LogOut, Menu, X, ChevronRight, Layers3, Bell, Inbox} from 'lucide-react';
import {useAuth} from '../../auth/AuthProvider';
import {Brand} from '../shared/Common';
import {Button} from '../ui/button';
import {api, errorMessage} from '../../api/client';
import {toast} from 'sonner';
const links = [ ['/operations','Overview',LayoutDashboard], ['/operations/transactions','Transactions',GitBranch], ['/operations/reviews','Review inbox',Inbox], ['/operations/connectors','Connectors',PlugZap], ['/operations/mappings','Schema mappings',Braces], ['/operations/exceptions','Exceptions',CircleAlert], ['/operations/policy','Policy & consent',ShieldCheck], ['/operations/audit','Audit trail',ScrollText], ['/operations/health','System health',HeartPulse] ] as const;
const officialLinks = [ ['/operations/reviews','Review inbox',Inbox], ['/operations/transactions','Department cases',GitBranch], ['/operations/policy','Policy & consent',ShieldCheck], ['/operations/audit','Audit trail',ScrollText] ] as const;
export const AppShell = () => {
  const {user,logout}=useAuth(); const [open,setOpen]=useState(false); const location=useLocation();
  const citizen=user.role==='citizen', official=user.role==='official';
  const nav:ReadonlyArray<readonly [string,string,typeof LayoutDashboard]>=citizen?[['/citizen','My applications',LayoutDashboard],['/citizen/new','Start a service',Layers3],['/citizen/notifications','Notifications',Bell]]:official?officialLinks:links;
  const current=nav.find(v=>v[0]===location.pathname)?.[1] || (citizen?'Application details':official?'Case file':'Transaction details');
  return <div className="app-shell">
    {open&&<button data-testid="navigation-backdrop" className="nav-backdrop" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}
    <aside className={`sidebar ${open?'is-open':''}`}><Brand/><div className="workspace-label" data-testid="workspace-label"><span className="tiny-square"/>{citizen?'CITIZEN WORKSPACE':official?'DEPARTMENT WORKSPACE':'OPERATIONS WORKSPACE'}</div><nav>{nav.map(([path,text,Icon])=><NavLink data-testid={`nav-${path.split('/').pop()}`} key={path} to={path} end onClick={()=>setOpen(false)} className={({isActive})=>`nav-link ${isActive?'active':''}`}><Icon size={18}/>{text}{path===location.pathname&&<ChevronRight className="nav-arrow" size={14}/>}</NavLink>)}</nav><div className="sidebar-bottom"><div className="demo-notice" data-testid="demo-notice"><span className="demo-dot"/>SIH 2026 · Prototype<span>Synthetic data · Simulated departments</span></div><div className="user-row"><div className="avatar">{user.name.split(' ').map((n:string)=>n[0]).slice(0,2).join('')}</div><div className="user-text" data-testid="current-user"><strong>{user.name}</strong><span>{citizen?'Citizen':user.role==='operator'?'Platform operator':user.designation||user.role}</span></div><button data-testid="logout-button" title="Sign out" aria-label="Sign out" onClick={()=>logout().catch((e:any)=>toast.error(errorMessage(e)))}><LogOut size={16}/></button></div></div></aside>
    <div className="workspace"><header className="topbar"><button data-testid="mobile-navigation-toggle" className="mobile-menu" aria-label="Open navigation" onClick={()=>setOpen(!open)}>{open?<X size={21}/>:<Menu size={21}/>}</button><div className="breadcrumbs" data-testid="breadcrumbs"><span>{citizen?'Citizen portal':official?'Department workspace':'Interoperability layer'}</span><ChevronRight size={13}/><strong>{current}</strong></div><div className="topbar-right"><span className="environment" data-testid="environment-badge">SANDBOX</span><span className="state-mark"/> <span className="region-label" data-testid="region-label">Maharashtra, India</span></div></header><main><Outlet/></main><footer data-testid="workspace-footer"><span>Sampark · Government service orchestration</span><span>SIH26129 <span className="footer-dot">·</span> Prototype v1.0</span></footer></div>
  </div>;
};