import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {FlaskConical, CheckCircle2, Timer, Unplug, ArrowRight, UserCheck, Zap} from 'lucide-react';
import {Dialog, DialogContent, DialogTitle, DialogDescription} from '../ui/dialog';
import {Button} from '../ui/button';
import {api, errorMessage} from '../../api/client';
import {useSchemes} from '../shared/Scheme';
import {rupees} from '../../api/contracts';
import {toast} from 'sonner';
export const DemoDialog = ({open, onOpenChange}: {open:boolean; onOpenChange:(v:boolean)=>void}) => {
 const [scenario,setScenario]=useState('success'),[scheme,setScheme]=useState('MH_SKILL_BENEFIT'),[review,setReview]=useState<'manual'|'auto'>('manual'),[busy,setBusy]=useState(false);const navigate=useNavigate();const schemes=useSchemes().data||[];
 const start=async()=>{setBusy(true);try{const {data}=await api.post('/demo/journeys',{scenario,review,service_code:scheme},{headers:{'Idempotency-Key':crypto.randomUUID()}});onOpenChange(false);navigate(`/operations/transactions/${data.transaction_id}`);toast.success(review==='manual'?'Demo journey created · the department officer must sanction it':'Demo journey created');}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}};
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent data-testid="demo-journey-dialog" className="product-dialog"><div className="dialog-icon"><FlaskConical size={24}/></div><DialogTitle data-testid="demo-dialog-title">Start a demo journey</DialogTitle><DialogDescription data-testid="demo-dialog-description">Applicant Aditi Patil · Synthetic data and consent</DialogDescription><span className="field-label" data-testid="demo-scheme-label">SCHEME</span><select className="dialog-select" data-testid="demo-scheme-select" aria-label="Scheme" value={scheme} onChange={e=>setScheme(e.target.value)}>{schemes.map(s=><option key={s.code} value={s.code}>{s.name} · {rupees(s.amount)}</option>)}</select><span className="field-label" data-testid="demo-scenario-label">SCENARIO</span><div className="scenario-options">{[['success','Successful journey','All three departments complete the service.',CheckCircle2],['timeout_after_commit','Treasury timeout','Payment commits, but the response times out.',Timer],['treasury_unavailable','Treasury unavailable','A recoverable downstream service failure.',Unplug]].map(([id,title,desc,Icon]:any)=><button key={id} data-testid={`scenario-${id}`} className={scenario===id?'selected':''} onClick={()=>setScenario(id)}><Icon size={21}/><span><strong>{title}</strong><small>{desc}</small></span><span className="radio-indicator"/></button>)}</div><span className="field-label" data-testid="review-mode-label">DEPARTMENT APPROVAL</span><div className="review-mode-options">{[['manual','Officer decides','Waits in the department review inbox until an officer sanctions it.',UserCheck],['auto','Auto-sanction','Skips the officer step so failure drills reach the treasury immediately.',Zap]].map(([id,title,desc,Icon]:any)=><button key={id} data-testid={`review-mode-${id}`} className={review===id?'selected':''} onClick={()=>setReview(id)}><Icon size={17}/><span><strong>{title}</strong><small>{desc}</small></span></button>)}</div><Button data-testid="start-demo-journey" disabled={busy} className="primary-button" onClick={start}>{busy?'Creating journey…':'Start journey'}<ArrowRight size={16}/></Button></DialogContent></Dialog>;
};
