import {useState} from 'react';
import {Radio,ScrollText,ShieldCheck,Check,ArrowRight} from 'lucide-react';
import {Button} from '../ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../ui/dialog';
import {Textarea} from '../ui/textarea';
import {StatusBadge,label} from '../shared/StatusBadge';
import {DateText,Empty} from '../shared/Common';
import {api,errorMessage} from '../../api/client';
import {toast} from 'sonner';
export const EvidenceTabs=({app,tab,citizen,refresh}:any)=>{
 const [revoke,setRevoke]=useState<any>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);
 const withdraw=async()=>{setBusy(true);try{await api.post(`/applications/${app.id}/consents/${revoke.id}/revoke`,{reason});setRevoke(null);toast.success('Consent revoked for future exchanges');refresh();}catch(e){toast.error(errorMessage(e));}finally{setBusy(false)}};
 if(tab==='consent')return <section className="consent-records"><div className="section-heading"><h2 data-testid="consent-records-title">Transaction-scoped consent</h2><span className="subtle">Policy v1 · 30-day validity</span></div>{app.consents.map((c:any)=><div className="consent-record" key={c.id} data-testid={`consent-record-${c.id}`}><div className="consent-record-heading"><ShieldCheck size={21}/><div><h3>{c.recipient==='eligibility'?'Skill Development':'State Treasury'}</h3><span className="mono">{c.id}</span></div><StatusBadge status={c.state} id={`consent-state-${c.id}`}/></div><p data-testid={`consent-purpose-${c.id}`}>{label(c.purpose)}</p><div className="field-chips">{c.fields.map((f:string)=><code key={f}>{f}</code>)}</div><div className="consent-record-footer"><span data-testid={`consent-expiry-${c.id}`}>Granted <DateText value={c.granted_at}/> · Expires <DateText value={c.expires_at}/></span>{citizen&&c.state==='ACTIVE'&&<Button variant="outline" data-testid={`revoke-consent-${c.id}`} onClick={()=>{setRevoke(c);setReason('')}}>Revoke consent</Button>}</div></div>)}<Dialog open={!!revoke} onOpenChange={v=>!v&&setRevoke(null)}><DialogContent className="product-dialog" data-testid="revoke-dialog"><DialogTitle data-testid="revoke-title">Revoke data-sharing consent?</DialogTitle><DialogDescription data-testid="revoke-description">Future exchanges under this consent will stop. Completed actions, including a disbursement, cannot be undone.</DialogDescription><Textarea data-testid="revoke-reason" aria-label="Reason for revoking consent" placeholder="Reason for revocation" value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={300}/><Button data-testid="confirm-revoke" variant="destructive" disabled={busy||reason.trim().length<5} onClick={withdraw}>{busy?'Revoking…':'Revoke consent'}</Button></DialogContent></Dialog></section>;
 const rows=tab==='events'?app.events:app.audit;
 return <section className="event-section"><div className="section-heading"><h2 data-testid="evidence-log-title">{tab==='events'?'Event stream':'Audit trail'}</h2><span className="subtle" data-testid="evidence-log-count">{rows.length} records · UTC timestamps localized</span></div>{!rows.length?<Empty title="No records yet" description="Evidence appears as this service progresses."/>:<div className="event-list">{[...rows].reverse().map((e:any)=><div className="event-row" data-testid={`evidence-event-${e.id}`} key={e.id}><div className={`event-dot ${e.type==='POLICY_DENIED'||e.action==='POLICY_DENIED'?'deny':''}`}><span/></div><div className="event-main"><strong>{e.type||e.action}</strong><span><code>{e.id}</code> <span>·</span> {e.producer||e.actor}</span>{e.stream_id&&<small data-testid={`stream-id-${e.id}`}>Redis entry {e.stream_id}</small>}{(e.payload?.result||e.metadata?.result)&&<span className="event-result">{e.payload?.result||e.metadata?.result}</span>}</div><div className="event-time"><span>#{String(e.sequence).padStart(2,'0')}</span><DateText value={e.timestamp}/></div></div>)}</div>}</section>;
};