import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {Search,Plus,SlidersHorizontal,ArrowRight,GraduationCap,ShieldCheck,Clock3} from 'lucide-react';
import {get} from '../api/client';
import {useAuth} from '../auth/AuthProvider';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {PageHeader,Loading,ErrorState} from '../components/shared/Common';
import {ApplicationTable} from '../components/transactions/ApplicationTable';
import {DemoDialog} from '../components/transactions/DemoDialog';
export default function ApplicationsPage({exceptions=false}: {exceptions?:boolean}){
 const {user}=useAuth();const citizen=user.role==='citizen';const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[cursor,setCursor]=useState(''),[demo,setDemo]=useState(false);
 const q=useQuery({queryKey:['applications',search,status,cursor,exceptions,user.id],queryFn:()=>get(`/applications?limit=20&search=${encodeURIComponent(search)}&status=${status}&cursor=${cursor}&attention=${exceptions}`),refetchInterval:3000});
 let items=q.data?.items||[];if(exceptions)items=items.filter((a:any)=>['RECONCILING','RETRY_SCHEDULED','HUMAN_INTERVENTION_REQUIRED','BLOCKED'].includes(a.status));
 return <><PageHeader eyebrow={citizen?'CITIZEN PORTAL':'SERVICE ORCHESTRATION'} title={citizen?'My applications':exceptions?'Exceptions & recovery':'Transactions'} description={citizen?`Welcome back, ${user.name.split(' ')[0]}. Your services, all in one place.`:exceptions?'Unresolved integrations and workflows awaiting attention.':'Every service journey. One traceable lifecycle.'} action={citizen?<Button asChild className="primary-button" data-testid="new-application-link"><Link to="/citizen/new"><Plus size={16}/>Start a new service</Link></Button>:user.role==='operator'?<Button data-testid="new-demo-journey" className="primary-button" onClick={()=>setDemo(true)}><Plus size={16}/>New demo journey</Button>:null}/>{citizen&&<section className="citizen-service-band"><div className="service-symbol"><GraduationCap size={32}/></div><div><span className="eyebrow" data-testid="available-service-label">AVAILABLE SERVICE · DEMO</span><h2 data-testid="available-service-title">Skill development benefit</h2><p data-testid="available-service-description">Training support for your next chapter.</p></div><div className="benefit-value" data-testid="benefit-value">₹15,000<span>Training benefit</span></div><Button variant="outline" asChild data-testid="explore-service-link"><Link to="/citizen/new">Apply now<ArrowRight size={16}/></Link></Button></section>}<div className="list-toolbar"><div className="search-field"><Search size={17}/><Input data-testid="application-search" aria-label="Search applications" placeholder="Search application, transaction or citizen…" value={search} onChange={e=>{setSearch(e.target.value);setCursor('')}}/></div><div className="filter-field"><SlidersHorizontal size={15}/><select data-testid="application-status-filter" aria-label="Filter by status" value={status} onChange={e=>{setStatus(e.target.value);setCursor('')}}><option value="">All statuses</option>{['SUBMITTED','PROCESSING','COMPLETED','RECONCILING','RETRY_SCHEDULED','HUMAN_INTERVENTION_REQUIRED','BLOCKED','REJECTED'].map(s=><option key={s} value={s}>{s.toLowerCase().replaceAll('_',' ')}</option>)}</select></div><span className="result-count" data-testid="application-count">{exceptions?items.length:q.data?.total||0} {citizen?'applications':'transactions'}</span></div>{q.isLoading?<Loading/>:q.isError?<ErrorState retry={q.refetch} error={q.error}/>:<ApplicationTable items={items} citizen={citizen}/>}<div className="pagination">{cursor&&<Button variant="outline" data-testid="pagination-first" onClick={()=>setCursor('')}>Back to latest</Button>}{q.data?.next_cursor&&<Button variant="outline" data-testid="pagination-next" onClick={()=>setCursor(q.data.next_cursor)}>Next page<ArrowRight size={15}/></Button>}</div><DemoDialog open={demo} onOpenChange={setDemo}/></>;
}