import {useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {Search,Plus,SlidersHorizontal,ArrowRight,Layers3} from 'lucide-react';
import {get} from '../api/client';
import {useAuth} from '../auth/AuthProvider';
import {Button} from '../components/ui/button';
import {Input} from '../components/ui/input';
import {PageHeader,Loading,ErrorState} from '../components/shared/Common';
import {SchemeIcon,useSchemes} from '../components/shared/Scheme';
import {ApplicationTable} from '../components/transactions/ApplicationTable';
import {DemoDialog} from '../components/transactions/DemoDialog';
import {rupees} from '../api/contracts';
export default function ApplicationsPage({exceptions=false}: {exceptions?:boolean}){
 const {user}=useAuth();const citizen=user.role==='citizen';const [params]=useSearchParams();const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[scheme,setScheme]=useState(params.get('scheme')||''),[cursor,setCursor]=useState(''),[demo,setDemo]=useState(false);
 const schemes=useSchemes().data||[];
 const q=useQuery({queryKey:['applications',search,status,scheme,cursor,exceptions,user.id],queryFn:()=>get(`/applications?limit=20&search=${encodeURIComponent(search)}&status=${status}&service_code=${scheme}&cursor=${cursor}&attention=${exceptions}`),refetchInterval:3000});
 let items=q.data?.items||[];if(exceptions)items=items.filter((a:any)=>['RECONCILING','RETRY_SCHEDULED','HUMAN_INTERVENTION_REQUIRED','BLOCKED'].includes(a.status));
 return <><PageHeader eyebrow={citizen?'CITIZEN PORTAL':'SERVICE ORCHESTRATION'} title={citizen?'My applications':exceptions?'Exceptions & recovery':'Transactions'} description={citizen?`Welcome back, ${user.name.split(' ')[0]}. Your services, all in one place.`:exceptions?'Unresolved integrations and workflows awaiting attention.':'Every service journey. One traceable lifecycle.'} action={citizen?<Button asChild className="primary-button" data-testid="new-application-link"><Link to="/citizen/new"><Plus size={16}/>Start a new service</Link></Button>:user.role==='operator'?<Button data-testid="new-demo-journey" className="primary-button" onClick={()=>setDemo(true)}><Plus size={16}/>New demo journey</Button>:null}/>
 {citizen&&<section className="catalogue" data-testid="service-catalogue"><div className="section-heading"><div><h2 data-testid="catalogue-title">Available services</h2><p data-testid="catalogue-description">Three departments. One application experience.</p></div></div><div className="catalogue-grid">{schemes.map(s=><article key={s.code} className={`catalogue-card ${s.unit}`} data-testid={`catalogue-${s.code}`}><div className="catalogue-top"><span className="service-symbol"><SchemeIcon icon={s.icon} size={26}/></span><span className="catalogue-amount" data-testid={`catalogue-amount-${s.code}`}>{rupees(s.amount)}</span></div><span className="eyebrow">{s.department.toUpperCase()}</span><h3>{s.name}</h3><p>{s.description}</p><small>{s.eligibility}</small><Button variant="outline" asChild data-testid={`apply-${s.code}`}><Link to={`/citizen/new?scheme=${s.code}`}>Apply now<ArrowRight size={15}/></Link></Button></article>)}</div></section>}
 <div className="list-toolbar">{!citizen&&<div className="search-field"><Search size={17}/><Input data-testid="application-search" aria-label="Search applications" placeholder="Search application, transaction or citizen…" value={search} onChange={e=>{setSearch(e.target.value);setCursor('')}}/></div>}{!citizen&&<div className="filter-field"><Layers3 size={15}/><select data-testid="application-scheme-filter" aria-label="Filter by scheme" value={scheme} onChange={e=>{setScheme(e.target.value);setCursor('')}}><option value="">All schemes</option>{schemes.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></div>}{!citizen&&<div className="filter-field"><SlidersHorizontal size={15}/><select data-testid="application-status-filter" aria-label="Filter by status" value={status} onChange={e=>{setStatus(e.target.value);setCursor('')}}><option value="">All statuses</option>{['SUBMITTED','PROCESSING','UNDER_REVIEW','COMPLETED','RECONCILING','RETRY_SCHEDULED','HUMAN_INTERVENTION_REQUIRED','BLOCKED','REJECTED'].map(s=><option key={s} value={s}>{s.toLowerCase().replaceAll('_',' ')}</option>)}</select></div>}{citizen&&<h2 className="list-title" data-testid="my-applications-title">My applications</h2>}<span className="result-count" data-testid="application-count">{exceptions?items.length:q.data?.total||0} {citizen?'applications':'transactions'}</span></div>{q.isLoading?<Loading/>:q.isError?<ErrorState retry={q.refetch} error={q.error}/>:<ApplicationTable items={items} citizen={citizen}/>}<div className="pagination">{cursor&&<Button variant="outline" data-testid="pagination-first" onClick={()=>setCursor('')}>Back to latest</Button>}{q.data?.next_cursor&&<Button variant="outline" data-testid="pagination-next" onClick={()=>setCursor(q.data.next_cursor)}>Next page<ArrowRight size={15}/></Button>}</div><DemoDialog open={demo} onOpenChange={setDemo}/></>;
}
