import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {Search,ArrowUpRight,ScrollText} from 'lucide-react';
import {get} from '../api/client';
import {Input} from '../components/ui/input';
import {PageHeader,Loading,ErrorState,Empty,DateText} from '../components/shared/Common';
export default function AuditPage(){
 const [search,setSearch]=useState(''),[expanded,setExpanded]=useState('');
 const q=useQuery({queryKey:['audit',search],queryFn:()=>get(`/audit?search=${encodeURIComponent(search)}`),refetchInterval:5000});
 return <><PageHeader eyebrow="EVIDENCE & PROVENANCE" title="Audit trail" description="Who acted, what changed, and why it was permitted."/><div className="list-toolbar"><div className="search-field"><Search size={17}/><Input data-testid="audit-search" placeholder="Search transaction ID…" aria-label="Search audit transactions" value={search} onChange={e=>setSearch(e.target.value)}/></div><span className="result-count" data-testid="audit-result-count">Latest {q.data?.items.length||0} records</span></div>{q.isLoading?<Loading/>:q.isError?<ErrorState retry={q.refetch}/>:!q.data.items.length?<Empty title="No audit records" description="Transaction evidence will appear as services run."/>:<div className="audit-table"><div className="audit-table-heading"><span>TIMESTAMP</span><span>ACTION / ACTOR</span><span>TRANSACTION</span><span>RESULT</span></div>{q.data.items.map((e:any)=><div className="audit-entry" key={e.id}><button data-testid={`audit-entry-${e.id}`} className="audit-entry-main" onClick={()=>setExpanded(expanded===e.id?'':e.id)}><span className="audit-time"><DateText value={e.timestamp}/></span><span className="audit-action"><strong className={e.action==='POLICY_DENIED'?'denied-text':''}>{e.action}</strong><small>{e.actor}</small></span><code>{e.transaction_id}</code><span className={`audit-result ${e.action==='POLICY_DENIED'?'denied-text':''}`}>{e.result}</span></button>{expanded===e.id&&<div className="audit-expanded" data-testid={`audit-expanded-${e.id}`}><pre>{JSON.stringify(e.metadata,null,2)}</pre><Link data-testid={`audit-transaction-${e.id}`} className="text-link" to={`/operations/transactions/${e.transaction_id}`}>Open transaction<ArrowUpRight size={15}/></Link></div>}</div>)}</div>}</>;
}