import {useRef,useState} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {ShieldCheck,ArrowLeft,ArrowRight,UserRound,Check} from 'lucide-react';
import {useAuth} from '../auth/AuthProvider';
import {api,errorMessage} from '../api/client';
import {Button} from '../components/ui/button';
import {Checkbox} from '../components/ui/checkbox';
import {PageHeader,Loading,ErrorState} from '../components/shared/Common';
import {SchemeIcon,useSchemes} from '../components/shared/Scheme';
import {rupees} from '../api/contracts';
import {toast} from 'sonner';
export default function NewApplicationPage(){
 const {user}=useAuth(),navigate=useNavigate();const [params,setParams]=useSearchParams();const schemesQ=useSchemes();const schemes=schemesQ.data||[];
 const key=useRef(crypto.randomUUID());const [option,setOption]=useState(''),[district,setDistrict]=useState('Pune'),[eligibility,setEligibility]=useState(false),[payment,setPayment]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(schemesQ.isLoading)return <Loading/>;if(schemesQ.isError||!schemes.length)return <ErrorState retry={schemesQ.refetch} error={schemesQ.error}/>;
 const scheme=schemes.find(s=>s.code===params.get('scheme'))||schemes[0];const opt=scheme.options.some(o=>o.code===option)?option:scheme.options[0].code;
 const reset=()=>{key.current=crypto.randomUUID();setError('')};
 const pick=(code:string)=>{setParams({scheme:code});setOption('');reset()};
 const submit=async(e:any)=>{e.preventDefault();if(!eligibility||!payment){setError('Both consent permissions are required to start this service.');return;}setBusy(true);setError('');try{const {data}=await api.post('/applications',{service_code:scheme.code,option_code:opt,district,eligibility_consent:eligibility,payment_consent:payment},{headers:{'Idempotency-Key':key.current}});toast.success('Application submitted');navigate(`/citizen/applications/${data.id}`);}catch(e){setError(errorMessage(e));}finally{setBusy(false)}};
 return <><Link to="/citizen" className="back-link" data-testid="back-to-citizen"><ArrowLeft size={15}/>My applications</Link><PageHeader eyebrow={`NEW APPLICATION · ${scheme.department.toUpperCase()}`} title={scheme.name} description={scheme.description}/><div className="application-form-layout"><form onSubmit={submit} className="service-form">
  <section className="form-section"><div className="form-section-title"><span>01</span><h2 data-testid="applicant-section-title">Applicant details</h2></div><div className="applicant-summary" data-testid="applicant-summary"><span className="applicant-avatar"><UserRound size={23}/></span><div><strong>{user.name}</strong><span>{user.email}</span></div><span className="verified-reference"><ShieldCheck size={14}/>Linked demo identity</span></div></section>
  <section className="form-section"><div className="form-section-title"><span>02</span><h2 data-testid="scheme-section-title">Choose a service</h2></div><div className="scheme-selector" role="radiogroup" data-testid="scheme-selector">{schemes.map(s=><button type="button" role="radio" aria-checked={s.code===scheme.code} key={s.code} data-testid={`scheme-option-${s.code}`} className={s.code===scheme.code?'selected':''} onClick={()=>pick(s.code)}><SchemeIcon icon={s.icon} size={19}/><span><strong>{s.name}</strong><small>{s.department} · {rupees(s.amount)}</small></span>{s.code===scheme.code&&<Check size={15}/>}</button>)}</div></section>
  <section className="form-section"><div className="form-section-title"><span>03</span><h2 data-testid="details-section-title">Application details</h2></div><div className="form-grid"><label data-testid="option-label">{scheme.option_label}<select data-testid="option-select" value={opt} onChange={e=>{setOption(e.target.value);reset()}}>{scheme.options.map(o=><option key={o.code} value={o.code}>{o.label}</option>)}</select></label><label data-testid="district-label">District<select data-testid="district-select" value={district} onChange={e=>{setDistrict(e.target.value);reset()}}>{scheme.districts.map(d=><option key={d}>{d}</option>)}</select></label></div><p className="consent-footnote" data-testid="eligibility-note"><ShieldCheck size={15}/>Eligibility: {scheme.eligibility}. The department system decides eligibility; an officer then sanctions the benefit.</p></section>
  <section className="form-section"><div className="form-section-title"><span>04</span><h2 data-testid="consent-section-title">Data-sharing consent</h2></div><label className="consent-option" data-testid="eligibility-consent-label"><Checkbox data-testid="eligibility-consent" checked={eligibility} onCheckedChange={v=>setEligibility(v===true)}/><span><strong>Eligibility verification</strong><p>Allow the {scheme.department} department to access your birth date, identity verification result, person reference, {scheme.option_label.toLowerCase()} and eligibility status for this application.</p><small>Purpose: Benefit eligibility · Valid for 30 days</small></span></label><label className="consent-option" data-testid="payment-consent-label"><Checkbox data-testid="payment-consent" checked={payment} onCheckedChange={v=>setPayment(v===true)}/><span><strong>Benefit disbursement</strong><p>Allow State Treasury to receive the approval reference, payee reference and approved amount. Bank account details are not collected here.</p><small>Purpose: Benefit disbursement · Valid for 30 days</small></span></label><p className="consent-footnote" data-testid="consent-footnote"><ShieldCheck size={15}/>You can revoke consent from your application. Revocation stops future sharing, not completed actions.</p></section>
  {error&&<div role="alert" className="form-error" data-testid="application-form-error">{error}</div>}<div className="form-actions"><Button asChild variant="outline" data-testid="cancel-application"><Link to="/citizen">Cancel</Link></Button><Button data-testid="submit-application" type="submit" disabled={busy} className="primary-button">{busy?'Submitting…':'Submit application'}<ArrowRight size={16}/></Button></div></form>
  <aside className="benefit-summary" data-testid="benefit-summary"><SchemeIcon icon={scheme.icon} size={35}/><span className="eyebrow">{scheme.department.toUpperCase()}</span><strong data-testid="new-benefit-amount">{rupees(scheme.amount)}</strong><p data-testid="new-benefit-description">{scheme.description}</p><p className="subtle" data-testid="new-benefit-eligibility">{scheme.eligibility}</p><div className="summary-divider"/><h3 data-testid="journey-summary-title">Your service journey</h3>{scheme.stages.map((s,i)=><div className="summary-stage" key={s.id} data-testid={`summary-stage-${i}`}><span>{i+1}</span><div>{s.name} <em>· {s.system}</em></div></div>)}<div className="synthetic-note" data-testid="synthetic-note">Prototype service. Departments are simulated; no real funds are transferred.</div></aside></div></>;
}
