import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Activity, ArrowRight, ArrowUpRight, CheckCheck, CircleAlert, Fingerprint, GraduationCap, Landmark, GitBranch, Network, Plus, ShieldCheck, Radio, RefreshCw, DatabaseZap} from 'lucide-react';
import {api,get,errorMessage} from '../api/client';
import {useAuth} from '../auth/AuthProvider';
import {Button} from '../components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {PageHeader,Loading,ErrorState} from '../components/shared/Common';
import {StatusBadge} from '../components/shared/StatusBadge';
import {ApplicationTable} from '../components/transactions/ApplicationTable';
import {DemoDialog} from '../components/transactions/DemoDialog';
import {rupees} from '../api/contracts';
import {toast} from 'sonner';
const icons:any={registry:Fingerprint,eligibility:GraduationCap,treasury:Landmark};
export default function OverviewPage(){
 const {user}=useAuth();const [demo,setDemo]=useState(false),[reset,setReset]=useState(false),[busy,setBusy]=useState(false);const queries=useQueryClient();
 const q=useQuery({queryKey:['overview'],queryFn:()=>get('/monitoring/overview'),refetchInterval:4000});
 const doReset=async()=>{setBusy(true);try{const {data}=await api.post('/demo/dataset/reset');toast.success(`Demo history regenerated · ${data.seeded} applications`);setReset(false);queries.invalidateQueries();}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}};
 if(q.isLoading)return <Loading/>;if(q.isError)return <ErrorState retry={q.refetch} error={q.error}/>;const d=q.data;
 const metrics=[['Total applications',d.total,GitBranch,`${d.by_scheme?.length||0} schemes · 3 departments`,'mint'],['Integration success',d.success_rate===null?'—':`${d.success_rate}%`,CheckCheck,'Successful department attempts','blue'],['Active workflows',d.active,Activity,d.awaiting_review?`${d.awaiting_review} awaiting officer decision`:'Currently moving between systems','mint'],['Needs attention',d.attention,CircleAlert,'Recovery or review required','amber']];
 return <><PageHeader eyebrow="INTEROPERABILITY LAYER" title="Operations overview" description="One connected view of cross-department services." action={<div className="heading-actions"><Button data-testid="refresh-overview" variant="outline" className="icon-button" title="Refresh overview" onClick={()=>q.refetch()}><RefreshCw size={16}/></Button>{user.role==='operator'&&<Button data-testid="reset-demo-data" variant="outline" className="icon-button" title="Regenerate demo history" onClick={()=>setReset(true)}><DatabaseZap size={16}/></Button>}{user.role==='operator'&&<Button data-testid="new-demo-journey" className="primary-button" onClick={()=>setDemo(true)}><Plus size={16}/>New demo journey</Button>}</div>}/><div className="live-strip" data-testid="live-status-strip"><span><span className={`live-dot ${d.infrastructure.consumer==='HEALTHY'?'':'offline'}`}/>{d.infrastructure.consumer==='HEALTHY'?'Event consumer connected':'Event consumer unavailable'}</span><span>Redis Streams <span className="strip-divider">/</span> Canonical schema v1 <span className="strip-divider">/</span> Benefit workflow v1</span><span className="live-label">LIVE WORKSPACE</span></div><div className="metrics-grid">{metrics.map(([name,value,Icon,caption,tone]:any,i)=><div className="metric" key={name} data-testid={`metric-${i}`}><div className="metric-top"><span>{name}</span><span className={`metric-icon ${tone}`}><Icon size={17}/></span></div><div className="metric-value">{value}</div><span className="metric-caption">{caption}</span></div>)}</div>
 <section className="section-band"><div className="section-heading"><div><h2 data-testid="scheme-portfolio-title">Scheme portfolio</h2><p data-testid="scheme-portfolio-description">Each scheme is owned by its department; the fabric only coordinates.</p></div><Link className="text-link" to="/operations/reviews" data-testid="portfolio-reviews-link">Review inbox<ArrowUpRight size={15}/></Link></div><div className="scheme-table" data-testid="scheme-table"><div className="scheme-table-heading"><span>SCHEME</span><span>APPLICATIONS</span><span>COMPLETED</span><span>AWAITING OFFICER</span><span>ATTENTION</span><span>DISBURSED</span></div>{(d.by_scheme||[]).map((s:any)=><Link key={s.code} to={`/operations/transactions?scheme=${s.code}`} className="scheme-row" data-testid={`scheme-row-${s.code}`}><div className="scheme-cell"><strong>{s.name}</strong><small>{s.department} · {rupees(s.amount)} per beneficiary</small></div><span data-testid={`scheme-total-${s.code}`}>{s.total}</span><span>{s.completed}</span><span className={s.awaiting_review?'accent':''} data-testid={`scheme-awaiting-${s.code}`}>{s.awaiting_review}</span><span className={s.attention?'warn':''}>{s.attention}</span><span className="mono">{rupees(s.disbursed)}</span></Link>)}</div></section>
 <section className="section-band"><div className="section-heading"><div><h2 data-testid="fabric-title">The interoperability fabric</h2><p data-testid="fabric-description">Independent department systems. One coordinated service.</p></div><Link data-testid="view-connectors-link" className="text-link" to="/operations/connectors">Connector registry <ArrowUpRight size={15}/></Link></div><div className="fabric-visual"><div className="fabric-central"><span className="fabric-icon"><Network size={24}/></span><div data-testid="fabric-center"><strong>Sampark orchestration core</strong><span>Correlate <i>·</i> Normalize <i>·</i> Orchestrate</span></div><span className="core-version">v1.0</span></div><div className="fabric-stem"/><div className="connector-grid">{d.components.map((c:any)=>{const Icon=icons[c.id];return <Link key={c.id} data-testid={`connector-card-${c.id}`} to="/operations/connectors" className={`connector-card ${c.color}`}><div className="connector-top"><div className={`connector-icon ${c.color}`}><Icon size={22}/></div><StatusBadge status={c.health} id={`connector-health-${c.id}`}/></div><h3>{c.name}</h3><p>{c.department} <span>·</span> Simulated system</p><div className="connector-meta"><span className="protocol">{c.protocol}</span><span>{c.latency_ms===null?'No traffic':`${c.latency_ms} ms`} <ArrowUpRight size={13}/></span></div></Link>})}</div><div className="fabric-bottom"><span data-testid="canonical-signal"><ShieldCheck size={14}/>Policy-aware data exchange</span><span data-testid="events-signal"><Radio size={14}/>{d.events} durable events recorded</span><span data-testid="source-signal"><CheckCheck size={14}/>Departments remain authoritative</span></div></div></section><section className="section-band recent-section"><div className="section-heading"><div><h2 data-testid="recent-title">Recent service journeys</h2><p data-testid="recent-description">A single transaction across every department.</p></div><Link className="text-link" to="/operations/transactions" data-testid="all-transactions-link">View all transactions<ArrowRight size={15}/></Link></div><ApplicationTable items={d.recent}/></section><DemoDialog open={demo} onOpenChange={setDemo}/>
 <Dialog open={reset} onOpenChange={setReset}><DialogContent data-testid="reset-demo-dialog" className="product-dialog"><div className="dialog-icon"><DatabaseZap size={24}/></div><DialogTitle data-testid="reset-demo-title">Regenerate demo history?</DialogTitle><DialogDescription data-testid="reset-demo-description">All applications, department records and payments in this sandbox will be replaced with a fresh synthetic history (about 40 applications across the three schemes, including officer inbox items and a small exception backlog). Demo accounts are kept.</DialogDescription><Button data-testid="confirm-reset-demo" className="primary-button" disabled={busy} onClick={doReset}><DatabaseZap size={15}/>{busy?'Regenerating…':'Regenerate demo history'}</Button></DialogContent></Dialog></>;
}
